version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/bss
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/bss/
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 2000
      runas: ubuntu